### ISSUE TITLE
Build system needs to be able to find org.apache.commons.jexl2 package

### ISSUE THREAD

**Issue by colinpalmer** [eclipse/richbeans#27]

**Comment by colinpalmer** [comment]
The dependencies have been updated so JEXL is no longer required, but I'm leaving this issue open because in the longer term we would like to be able to use it.

**Comment by gerring** [comment]
If you want to use it the right way to do this is to raise a CQ with eclipse foundation (or get me to) to have JEXL in orbit. Once in orbit we change our target to pick up the latest orbit update site and can make a dependency on jexl.

**Comment by colinpalmer** [comment]
There's already an approved CQ for JEXL 2: https://dev.eclipse.org/ipzilla/show_bug.cgi?id=5684

Could we just make use of that somehow? Or does it need a new CQ to get into Orbit?
