### ISSUE TITLE
GUI generator should have an openDialog() method

### ISSUE THREAD

**Issue by colinpalmer** [eclipse/richbeans#42]
Open questions:
- how should we get the parent shell?
- how should we get the window title?

It'd make things a bit complicated to have several methods to allow each of the shell and title to be optional. Possible solutions I can see are:
- don't bother allowing a shell to be passed in
- just use a default title
- pass a (probably optional) DialogConfig object, which has shell and title fields (and the scope for future additions if more options are needed)

Any thoughts?

**Comment by colinpalmer** [comment]
Also, I'd propose the method signature to be:
`public void openDialog(Object bean)`
rather than:
`public <T> T openDialog(T bean)`
because we don't allow the object identity to change. It'll just have its fields edited in place, and client code can just continue using the object after it's been edited.

**Comment by gerring** [comment]
Perhaps API is similar to org.eclipse.jface.dialogs.MessageDialog?

public <T> T openConfirm(Shell parent, String title, T bean);

returns Modified T if they pressed ok or null if they pressed cancel.

**Comment by colinpalmer** [comment]
Implementing cancellation might not really be possible - the data binding from UI to model happens immediately whenever a value is changed so the object passed in will end up modified if the UI fields are edited. Because of that I haven't provided a cancel button in the dialog I've been using so far.

We could have it return an enum return code to indicate OK or CANCEL, and then client code could make a defensive copy of the object before giving it to the GUI generator and use the copy if the user cancels the dialog?

The only alternatives I can see would be to change data binding to happen only when the dialog is closed (but that'd be quite a big change from the way we're using it elsewhere and might require special treatment for the dialog) or insist that all objects used have to be copy-able in some way, but then we lose a lot of the flexibility that makes this really useful.

**Comment by gerring** [comment]
The service could clone the bean using something like DOEUtils.deepClone(...), that could be visualized and edited. If they press cancel, it returns null, if they press ok it returns the copy with their edits.

**Comment by colinpalmer** [comment]
Hmm, perhaps, but looking at DOEUtils, it seems we'd then need all our beans to implement Serializable, and there'd be OSGi-related classloading issues to worry about. I think to keep the generator as flexible as possible I'd rather go down the route of making custom only-on-OK data binding for the dialogs, if cancellation is a required feature.

For now, I'll start with a simple implementation using the existing data binding (and either only one OK button, or a CANCEL button as well but it's up to client code to deal with that by copying if required) because I already have the code to do that, but then we can think about improving the cancellation later if needed.

**Comment by gerring** [comment]
Ok

**Comment by colinpalmer** [comment]
OK, I've just pushed a basic implementation which should be all you need for a simple example. I'll leave this issue open because it would be nice to improve the data binding/cancellation thing at some point, and luckily (now I've looked into it a bit more) it doesn't look like it'll be too hard to do.
