### ISSUE TITLE
Tables instead of components.

### ISSUE THREAD

**Issue by gerring** [eclipse/richbeans#43]
A table mode would be nice for IGuiGeneratorService, generating the key value pairs in a searchable table.

**Comment by colinpalmer** [comment]
I agree, that would be useful and I've been considering doing it for a little while.

Any idea on how to nicely handle nested objects?

**Comment by gerring** [comment]
One way might be to allow the nested item to be a cell that when you click, you get a dialog with another table. It works and would be low cost to implement but is slightly less user friendly. My main use cases like scan config and detector config do not have that much nesting (or any that I know of).
