### ISSUE TITLE
The generator bundle should have tests on how to use the generator.

### ISSUE THREAD

**Issue by gerring** [eclipse/richbeans#7]
There should be tests to make it really easy for users to see how to auto-generate user interface using metawidgets and richbeans. We should copy in a few example beans and generate user interface using the generator and annotations and/or xml for the config.

**Comment by colinpalmer** [comment]
Do you mean tests, or just runnable Java examples? We already have a test runner in the test fragment, but I'd be keen to avoid putting a JUnit dependency in the main generator bundle.

**Comment by gerring** [comment]
I had in mind an SWTBot or similar with a much wider range of test beans, including nesting.
